### ISSUE TITLE
Notifications stuck on repo no longer access to

### ISSUE THREAD

**Issue by ringods** [octobox/octobox#628] opened 2018-05-02 07:13 UTC
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

Two months ago, I switched working for one customer to another. I still had some archived but unread notifications from repos I currently no longer have access to. These notifications are currently stuck. If I want to manipulate these, I get an error mentioning that my github token is invalid. See screenshot.

<img width="1792" alt="octoboxnotifications" src="https://user-images.githubusercontent.com/77923/39510019-8cbdee88-4de8-11e8-8e85-b92d4dfcb1eb.png">

🎯 **Goal**

I would like to keep my Octobox notification list clean.

💡 **Possible solutions**

Allow to remove such notifications from the list completely.

**Comment by chrisarcand** [comment] 2018-05-02 14:32
Dupe of #591 

Yeah definitely an issue we need to address.

**Closed** 2018-05-02 15:04 UTC
Labels: bug, duplicate

**Comment by andrew** [comment] 2018-07-30 11:45
This should be fixed now by #670
