### ISSUE TITLE
Cannot mark notifications as read or archive on octobox.io

### ISSUE THREAD

**Issue by RX14** [octobox/octobox#2260] opened 2020-03-01 18:00 UTC
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance
 
Marking notifications as read shows "Could not mark notification(s) read" error.

**Comment by andrew** [comment] 2020-03-01 20:37
@RX14 can you try logging out and back in again, I believe the issue is related to cookies and a recent puma security update, if it's still not working for you then I'll downgrade the version of puma again

**Comment by RX14** [comment] 2020-03-02 00:03
@andrew i signed out but signing in just takes me back to the homepage

**Comment by Koenkk** [comment] 2020-03-02 07:41
Exactly the same issue here, could not mark as read, after logout I cannot login anymore (just redirects back to homepage).

**Comment by andrew** [comment] 2020-03-02 10:06
I believe this should be fixed now, sorry for the delay

**Closed by andrew** 2020-03-02 10:06 UTC

**Comment by Koenkk** [comment] 2020-03-02 10:09
Fixed now indeed, thanks

**Comment by RX14** [comment] 2020-03-03 11:18
Thank you!
