### ISSUE TITLE
Ability to auto-archive closed PR's and Issues

### ISSUE THREAD

**Issue by gauntface** [octobox/octobox#893] opened 2018-09-07 22:49 UTC
Are you experiencing this issue in octobox.io or your own instance?
 - [X] octobox.io
 - [ ] My instance

🐞 **Problem**
At the moment octobox gets super noisy from renovate creating and merging PR's for upgrading packages.

🎯 **Goal**
By auto archiving a PR or issue when closed, it would highlight the issues and PR's that actually require my attention (i.e. which PR's were upgraded but failed status checks).

💡 **Possible solutions**
Maybe an option in settings that allows for auto-archiving.

**Comment by andrew** [comment] 2018-09-09 15:57
Duplicate of https://github.com/octobox/octobox/issues/8, which we'll be getting to very soon

**Closed by andrew** 2018-09-09 15:57 UTC
