### ISSUE TITLE
Support for reviewer request

### ISSUE THREAD

**Issue by WilsonChiang** [octobox/octobox#105] opened 2016-12-21 16:14 UTC
When someone adds you as a reviewer, it does not seem to send you a notification for it.

**Comment by tarebyte** [comment] 2016-12-21 16:14
@WilsonChiang if GitHub doesn't send a notification for it, we really don't have any way of knowing that the request happened.

So we might be out of luck here.

**Comment by andrew** [comment] 2016-12-21 16:28
Dupe of https://github.com/andrew/octobox/issues/99?

**Closed** 2016-12-27 22:43 UTC
Labels: duplicate
