### ISSUE TITLE
Notifications that are read on GitHub do not show on Octobox

### ISSUE THREAD

**Issue by GiacomoLaw** [octobox/octobox#263] opened 2017-01-19 09:58 UTC
If I read my notifications on GitHub by the bell, they don't show up on Octobox in the Inbox or the Archive.

**Comment by andrew** [comment] 2017-01-19 10:37
Dupe of https://github.com/octobox/octobox/issues/241

**Comment by GiacomoLaw** [comment] 2017-01-19 10:37
Okay, sorry.

**Closed by andrew** 2017-01-19 10:37 UTC
