### ISSUE TITLE
Show open / closed / merged status?

### ISSUE THREAD

**Issue by gauntface** [octobox/octobox#331] opened 2017-03-21 18:27 UTC
There are a few projects where the issue being closed / opened will dictate whether I'm interested in the change (i.e. personal projects I care about issues being opened / closed by someone, but larger projects - closing is done by a team member and requires no interaction).

It would be amazing to see the state of the PR / issue at the top level of octobox UI.

**Comment by chrisarcand** [comment] 2017-03-22 16:00
Dupe of #210, requires #4 first.

**Comment by andrew** [comment] 2017-08-22 16:53
Closing as a dupe but the first part of this has been merged in #411 and is available behind the `FETCH_SUBJECT` env var feature flag, docs here: https://github.com/octobox/octobox/blob/master/INSTALLATION.md#downloading-subjects

Still working on getting it available on https://octobox.io

**Closed by andrew** 2017-08-22 16:53 UTC
Labels: blocked, enhancement
