### ISSUE TITLE
Many controls require two taps on iPad

### ISSUE THREAD

**Issue by the-ress** [octobox/octobox#1308] opened 2018-11-29 07:14 UTC
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
On iPad I have to tap most of the controls twice - first tap only focuses it, second tap actually performs the action.

![07bc803b-bbd5-475e-9188-c6cd1963acea](https://user-images.githubusercontent.com/1612377/49205037-0c3d4080-f3ae-11e8-977e-6af16f3eb5d0.gif)

🎯 **Goal**
It won’t be that annoying to use octobox on iPad (and other touch devices).

💡 **Possible solutions**
https://css-tricks.com/annoying-mobile-double-tap-link-issue/

**Comment by andrew** [comment] 2018-11-29 10:43
I've noticed this when using the site on my iPhone occasionally too, definitely needs to be fixed, thanks for reporting 👍

**Comment by BenJam** [comment] 2019-01-04 14:36
inspecting this now. I have seen it before too.

**Comment by BenJam** [comment] 2019-01-04 16:41
So I've spent the last hour messiing about on this on numerous older and newer iOS devices. I'm half way between 'the hit areas are too small' and let's overide `.click` with `.onMouseEnter` on mobiles.

**Comment by andrew** [comment] 2019-01-04 17:52
@the-ress which version of iOS do you have on your ipad? I also upgraded the version of bootstrap recently and I'm unable to replicate the issue anymore, perhaps it's fixed?

**Comment by BenJam** [comment] 2019-01-07 09:19
Closing this for the moment, feel free to reopen if it pops up.

**Comment by andrew** [comment] 2019-01-16 11:13
@BenJam this is happening again since some of your mergers were deployed yesterday

**Comment by BenJam** [comment] 2019-01-17 07:05
Any of the controls I touched (I don't think I did) but there's more screwy scrolling I need to sort first.

**Comment by BenJam** [comment] 2019-01-17 09:55
takjng a look, @andrew suspects it's https://github.com/octobox/octobox/commit/da1f0c943a3e9ba58180e2a389f85a81f5336a95#diff-e1d1f343c9a5a0d9d9bb8765d2df358a

**Comment by BenJam** [comment] 2019-01-17 10:13
just backed that out over at https://octobox-benjam.herokuapp.com/ and the hover states still cause trouble. Backing it out entirely and only adding those rules on a media query might be best.

**Comment by BenJam** [comment] 2019-01-17 10:15
for example, the notification below is selected (see actions bar):

![img_6031](https://user-images.githubusercontent.com/158833/51311428-d4af5400-1a40-11e9-901d-44f5fe97d549.PNG)

**Comment by BenJam** [comment] 2019-01-17 10:23
looks like iOS now supports https://caniuse.com/#feat=css-media-interaction

**Comment by BenJam** [comment] 2019-01-17 11:09
I have a branch trying to get around this if anyone wants to check it out: https://github.com/octobox/octobox/tree/hover-buttons

**Comment by BenJam** [comment] 2019-01-17 14:20
had a go at this this morning:

- rolled back to last commit in Dec
- wrapped offending article in `@media (hover:hover)`
- removing the focus/hover buttons entirely

All with a similar conclusion: while I can get consistent clicks initially, as soon as I scroll and 'miss' a target area (which highlights the notification row) the interface does not reflect the state of the checkboxes.

**Comment by andrew** [comment] 2019-01-29 12:22
Just took a look at this, have pinpointed the exact lines of sass that are causing it:

https://github.com/octobox/octobox/blob/095c55bffb73500d5b38b0471d81984d6757b62b/app/assets/stylesheets/_notifications.scss#L137-L146

and 

https://github.com/octobox/octobox/blob/095c55bffb73500d5b38b0471d81984d6757b62b/app/assets/stylesheets/_notifications.scss#L189

Commenting out those two pieces fixes the double tap requirement, which is caused by the change in layout that is triggered by the display changes on hover/focus as originally pointed out by @the-ress in https://css-tricks.com/annoying-mobile-double-tap-link-issue/

I've wrapped the offending bits in `@media (hover:hover)` blocks in a PR over here: https://github.com/octobox/octobox/pull/1545

**Closed** 2019-01-29 12:58 UTC
Labels: bug, help wanted

**Comment by BenJam** [comment] 2019-01-29 13:04
I did this back when I last looked and still have the problem. But I think clicks are more consistent so no harm leaving it. Maybe it's a different bug:

![img_6062](https://user-images.githubusercontent.com/158833/51910145-41720900-23c6-11e9-8cf7-7cd8dd12d2a3.PNG)

Interface shows no checked box, but box is checked which is why actions are shown.

**Comment by andrew** [comment] 2019-01-29 13:09
@BenJam that's a bug with the custom checkbox implementation in bootstrap
