### ISSUE TITLE
Preview pane

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#209] opened 2017-01-02 23:19 UTC
What would you think of taking a page from https://notifications.githubapp.com and adding a preview pane?

**Comment by andrew** [comment] 2017-01-02 23:39
Dependent on #4, which is pretty involved and requires repo scope for private repos

**Comment by jerone** [comment] 2017-01-14 19:35
Duplicate of https://github.com/octobox/octobox/issues/69.

**Closed** 2017-01-14 20:01 UTC
Labels: enhancement, help wanted
