### ISSUE TITLE
Filter (out) comments that are only "+1"

### ISSUE THREAD

**Issue by laggingreflex** [octobox/octobox#188] opened 2016-12-29 22:58 UTC
Just found this (great project!)  so I'm not sure if this functionality exists. I want to filter out all comments in which the commenter has only replied with a small enough text that matches the pattern like "+1". 

I tried to do this in gmail with a filter like `+1 smaller:100` but the problem with gmail is that it probably counts the whole header or something, so if the cc or sender, or even a signature is longer or shorter it might miss or incorrectly include otherwise unwanted mails. It would've been great if gmail only considered the actual readable text message in its size filter. 

Is there such a filtering functionality in octobox? I'm looking around and it doesn't seem there is, but like I said I just found out about this so I'm not sure. 

If not, what would your thoughts be on adding such a feature?

**Comment by andrew** [comment] 2016-12-30 09:14
Related issue here: https://github.com/octobox/octobox/issues/8

Dependent on https://github.com/octobox/octobox/issues/4 as we don't have the body of the comment in the notification itself

**Comment by andrew** [comment] 2017-01-13 10:47
Going to close this as a duplicate of #8

**Closed by andrew** 2017-01-13 10:47 UTC
Labels: enhancement, help wanted
