### ISSUE TITLE
Incident 02/12/19 - Problem diagnosis and recovery guidance 

### ISSUE THREAD

**Issue by BenJam** [octobox/octobox#2125] opened 2019-12-03 10:14 UTC
It looks like, last night, Redis reached max memory around 22.48 GMT. 

We saw a number of failed requests and degraded experience from there until ~02.21 this morning. It looks like we recovered around 5pm when the max delay came back down. During this time we scaled to 10 dynos and got the queue back under control by ~5am. 

I'm not sure what caused this particular issue, it's a little concerned at it's outside of our peak traffic. I'd like to find out rather than blindly increasing the redis memory size and/or the maximum number of workers on Hirefire. 

So I thought I'd open an issue to document what I find and/or get a bit of a strategy for diagnosing issues for maintainers/on-call cover of Octobox.io

**Comment by andrew** [comment] 2019-12-03 21:41
I believe that the root cause of the problem is that we've maxed out the capacity of the postgresql instance on heroku, some queries are taking minutes to run at peak times. 

In the very short term, I'll try to reduce the amount of excess data we're storing in there by running some cleanup scripts but I'll have to look at moving octobox.io off of heroku within the next couple days as it's much too expensive to upgrade to the next postgresql plan on heroku.

**Comment by andrew** [comment] 2019-12-03 22:06
I've rolled out a sitewide database timeout of 10 seconds which should stop any queries from running for too long and choking the database but it will likely cause more user errors until we move the database. I'll make a plan to move it within the next couple days.

**Comment by andrew** [comment] 2019-12-15 19:35
I've moved almost everything off of heroku this evening, this will both significantly reduce the hosting costs of https://octobox.io and increase the performance of the database, although deployment is no longer automatic after pull requests are merged.

**Closed** 2019-12-16 10:25 UTC
Labels: octobox.io, support
