### ISSUE TITLE
Bubble up API errors to the end user

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#421] opened 2017-08-27 10:03 UTC
There are a couple classes of errors that happen which aren't technically application errors but we throw 500s for them:

- when the GitHub API is down
- when the API key is invalid

We should gracefully handle those errors and report them in the UI rather than throwing 500 errors

**Comment by chrisarcand** [comment] 2017-08-28 01:18
Duplicate of #382, going to close this one but add your points here :)

**Closed by chrisarcand** 2017-08-28 01:18 UTC
Labels: enhancement, help wanted

**Comment by andrew** [comment] 2017-08-28 02:56
👍 That'll teach me to open issues from my phone!
